[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "agentron"
version = "0.1.0"
description = "A Python library for building AI agents."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [{ name = "Saumitro Dasgupta", email = "sd@cs.stanford.edu" }]

[tool.setuptools.packages.find]
include = ["agentron*"]

[tool.setuptools.package-data]
agentron = ["dist/flux/**/*", "dist/webui/**/*"]

[tool.ruff]
line-length = 200
target-version = "py312"

[tool.ruff.format]
quote-style = "single"

[project.scripts]
agentron = "agentron.__main__:main"
