name: Publish
on: [push, workflow_dispatch]
jobs:
    build:
        name: Build distribution
        runs-on: ubuntu-latest

        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: latest

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.x'

            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  persist-credentials: false

            - name: Install Node.js dependencies
              run: npm install

            - name: Build Node.js packages
              run: npm run build

            - name: Build wheels
              run: python scripts/dist_build.py

            - name: Store the distribution packages
              uses: actions/upload-artifact@v6
              with:
                  name: python-package-distributions
                  path: dist/

    create-release:
        name: Create GitHub Release
        needs: [build]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v8
              with:
                  name: python-package-distributions
                  path: dist/

            - name: create release
              run: gh release create --draft --repo ${GITHUB_REPOSITORY} ${GITHUB_REF_NAME} dist/*
              env:
                  GH_TOKEN: ${{ github.token }}

    publish-to-pypi:
        name: Publish to PyPI
        needs: [build]
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/agentron
        permissions:
            id-token: write

        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v8
              with:
                  name: python-package-distributions
                  path: dist/

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
